name: AmongLegendMinecraft
version: 0.0.1
main: amonglegendminecraft.amonglegendminecraft.AmongLegendMinecraft
description: Minecraft Sussy Plugin
load: STARTUP
api-version: 1.19
Author: Moi
commands:
  start:
    description: "start the game"
    usage: /<command>
    aliases: [startGame,s]

  quest:
    description: "validateQuest"
    usage: /<command>
    aliases: [ValidateQuest,q]

  meeting:
    description: "meeting"
    usage: /<command>
    aliases: [MeetingCommand,m]

  vote:
    description: "vote"
    usage: /<command>
    aliases: [VoteCommand,v]

  sabotage:
    description: "sabotage"
    usage: /<command>
    aliases: [SabotageCommand,s]